function plot_l_curve_geometry(prior_file, gps_file, outfile, sel_prior_w, sel_gps_w, hl_frac)
% PLOT_L_CURVE_GEOMETRY  Compare recovered chamber geometry across L-curve sweeps.
%
%   Plots how each of the 16 inversion parameters (opt_params layout, see
%   get_full_m.m / CLAUDE.md) changes from one L-curve point to the next, for
%   BOTH the prior-weight sweep and the GPS-weight sweep, on a single figure.
%
%   Each subplot also shades the portion of every sweep whose weight is within
%   +/- hl_frac of the selected operating-point weight (the values used in the
%   actual inversion: prior_weight and gps_weight in optimize_geo_weighted_MCMC.m),
%   with a dashed line at the exact selected weight. The vertical extent of each
%   curve inside its shaded band shows how sensitive that geometry parameter is
%   to a +/-20% change in the chosen weight.
%
%   Two data formats are supported per file, detected automatically:
%     * optParams_list (16 x Nweights)          -- pattern-search L-curve output:
%       one optimal geometry per point, plotted as a line (no band).
%     * posteriors_list (16 x Nsamples x Nweights) -- MCMC L-curve output:
%       plotted as the posterior median line + 16-84th percentile band.
%
%   The pattern-search files now store the geometry because the driver's save
%   line (optimize_geo_weighted_MCMC.m, run_L_curve = true) writes optParams_list.
%   The *_geom.mat defaults were generated by re-running both sweeps headlessly.
%
%   Usage:
%       plot_l_curve_geometry                 % defaults to the *_geom pattern files
%       plot_l_curve_geometry(priorFile, gpsFile)
%       plot_l_curve_geometry(priorFile, gpsFile, outfile, selPriorW, selGpsW, frac)
%
%   Run from the repo root (paths are relative, like plotLcurve.m).

    if nargin < 1 || isempty(prior_file)
        prior_file = "Data/l_curve_data_prior_pattern_gps7_prior015_geom.mat";
    end
    if nargin < 2 || isempty(gps_file)
        gps_file = "Data/l_curve_data_gps_pattern_gps7_prior015_geom.mat";
    end
    if nargin < 3 || isempty(outfile)
        outfile = "./PaperFigs/l_curve_geometry_variation.png";
    end
    % Selected operating-point weights (optimize_geo_weighted_MCMC.m ~L294/L296).
    if nargin < 4 || isempty(sel_prior_w); sel_prior_w = 1.6e-1; end
    if nargin < 5 || isempty(sel_gps_w);   sel_gps_w   = 26;     end
    if nargin < 6 || isempty(hl_frac);     hl_frac     = 0.20;   end

    % Canonical opt_params ordering (must match paramNames in the driver).
    paramNames = {'dvHMM_insar','dvHMM_gps','volHMM','xHMM','yHMM','dHMM','alphaHMM', ...
                  'xSC','ySC','dSC','alphaSC','dipSC','strikeSC','dvSC_insar','dvSC_gps','volSC'};

    % Pretty title (TeX), unit scale factor, and unit label per parameter.
    titles = {'\DeltaV_{HMM} (InSAR)','\DeltaV_{HMM} (GPS)','V_{HMM}','x_{HMM}', ...
              'y_{HMM}','depth_{HMM}','\alpha_{HMM}','x_{SC}', ...
              'y_{SC}','depth_{SC}','\alpha_{SC}','dip_{SC}', ...
              'strike_{SC}','\DeltaV_{SC} (InSAR)','\DeltaV_{SC} (GPS)','V_{SC}'};
    scale  = [1e6 1e6 1e9 1   1 1 1 1   1 1 1 1   1 1e6 1e6 1e9];
    units  = {'10^6 m^3','10^6 m^3','10^9 m^3','m', ...
              'm','m','aspect','m', ...
              'm','m','aspect','deg', ...
              'deg','10^6 m^3','10^6 m^3','10^9 m^3'};

    % Pull the central geometry (+ band if MCMC) and normalized sweep position.
    P = get_sweep(prior_file, "prior_weights");
    G = get_sweep(gps_file,   "gps_weights");
    anyBand = P.hasBand || G.hasBand;

    % Normalized-position windows for weights within +/- hl_frac of the selected.
    P.hl = make_hl(P.w, sel_prior_w, hl_frac);
    G.hl = make_hl(G.w, sel_gps_w,   hl_frac);

    cPrior = [0    0.447 0.741];   % blue
    cGps   = [0.85 0.325 0.098];   % vermillion

    fig = figure('Color','w','Units','inches','Position',[1 1 16 13]); clf;
    t = tiledlayout(4, 4, 'Padding','compact', 'TileSpacing','compact');

    hP = []; hG = [];
    for i = 1:numel(paramNames)
        ax = nexttile; hold(ax,'on'); box(ax,'on'); grid(ax,'on');
        ax.GridAlpha = 0.15; ax.FontSize = 10;

        % Reference = each sweep's value at its selected weight (the "selected
        % MAP" solution). Curves are shown as a percent of this reference so both
        % sweeps pass through 100% at their selected weight. If the reference is
        % ~0 (e.g. yHMM pinned at its lower bound) percent is undefined, so fall
        % back to raw units for that subplot and flag it.
        [Pref, Pdeg] = ref_for(P, i, sel_prior_w);
        [Gref, Gdeg] = ref_for(G, i, sel_gps_w);
        deg = Pdeg || Gdeg;
        if ~deg
            tfP = @(y) 100 * y ./ Pref;
            tfG = @(y) 100 * y ./ Gref;
            ylab = '% of selected';
            ttl  = titles{i};
        else
            tfP = @(y) y ./ scale(i);
            tfG = @(y) y ./ scale(i);
            ylab = units{i};
            ttl  = [titles{i} ' (raw; sel\approx0)'];
        end

        % Highlight the +/-hl_frac weight window for each sweep (drawn first =
        % behind the data). Vertical span auto-fills the subplot height.
        draw_highlight(ax, P.hl, cPrior);
        draw_highlight(ax, G.hl, cGps);
        if ~deg
            yline(ax, 100, ':', 'Color', [0.5 0.5 0.5], 'LineWidth', 0.8, ...
                  'HandleVisibility', 'off');   % 100% = selected value
        end

        % Prior-weight sweep: band (MCMC only) then central line.
        if P.hasBand, band(ax, P.s, tfP(P.lo(i,:)), tfP(P.hi(i,:)), cPrior); end
        hp = plot(ax, P.s, tfP(P.med(i,:)), '-o', 'Color', cPrior, ...
                  'MarkerFaceColor', cPrior, 'MarkerSize', 3.5, 'LineWidth', 1.6);

        % GPS-weight sweep.
        if G.hasBand, band(ax, G.s, tfG(G.lo(i,:)), tfG(G.hi(i,:)), cGps); end
        hg = plot(ax, G.s, tfG(G.med(i,:)), '-s', 'Color', cGps, ...
                  'MarkerFaceColor', cGps, 'MarkerSize', 3.5, 'LineWidth', 1.6);

        title(ax, ttl, 'FontSize', 12, 'FontWeight','normal');
        ylabel(ax, ylab, 'FontSize', 9);
        xlim(ax, [-0.03 1.03]);
        if i > 12
            xlabel(ax, 'sweep position (weak \rightarrow strong)', 'FontSize', 9);
        end
        if i == 1, hP = hp; hG = hg; end
    end

    leg_h = [hP hG];
    leg_s = {sprintf('Prior-weight sweep (%.2g-%.2g);  shaded = %.2g \\pm%d%%', ...
                     min(P.w), max(P.w), sel_prior_w, round(hl_frac*100)), ...
             sprintf('GPS-weight sweep (%g-%g);  shaded = %g \\pm%d%%', ...
                     min(G.w), max(G.w), sel_gps_w, round(hl_frac*100))};
    if anyBand
        % Neutral proxy patch so the band legend entry reads as gray, not tinted.
        hB = patch(NaN, NaN, [0.6 0.6 0.6], 'FaceAlpha', 0.25, 'EdgeColor','none');
        leg_h = [leg_h hB];
        leg_s{end+1} = '16-84% posterior band';
    end
    lgd = legend(leg_h, leg_s, 'Orientation','horizontal', 'FontSize', 12, 'Box','off');
    lgd.Layout.Tile = 'north';

    if anyBand
        central = 'posterior median';
    else
        central = 'pattern-search optimum';
    end
    title(t, ['Geometry parameter variation across L-curve weight sweeps  (' central ', % of selected-weight value)'], ...
          'FontSize', 15, 'FontWeight','bold');

    if ~exist('PaperFigs','dir'); mkdir('PaperFigs'); end
    exportgraphics(fig, outfile, 'Resolution', 300);
    fprintf('Saved %s\n', outfile);
end

% ------------------------------------------------------------------------
function S = get_sweep(matfile, weight_var)
% Load geometry vs the swept weight from an L-curve .mat file. Handles two
% formats: pattern-search optParams_list (16 x Nweights, point estimate) and
% MCMC posteriors_list (16 x Nsamples x Nweights, reduced to median + 16/84).
    d = load(matfile);
    w = d.(char(weight_var))(:)';                    % 1 x Nweights (swept values)
    [w, order] = sort(w);                            % weak -> strong ordering

    if isfield(d, 'posteriors_list')
        pl = real(d.posteriors_list);
        pl = pl(:, :, order);
        S.med = squeeze(median(pl, 2));              % 16 x Nweights
        S.lo  = squeeze(prctile(pl, 16, 2));
        S.hi  = squeeze(prctile(pl, 84, 2));
        S.hasBand = true;
    elseif isfield(d, 'optParams_list')
        op = real(d.optParams_list);                 % 16 x Nweights
        S.med = op(:, order);
        S.lo = []; S.hi = [];
        S.hasBand = false;
    else
        error('%s has neither optParams_list nor posteriors_list (no geometry).', matfile);
    end
    if isscalar(w)                                   % keep column orientation for 1 pt
        S.med = S.med(:);
        if S.hasBand, S.lo = S.lo(:); S.hi = S.hi(:); end
    end

    % Drop any unfilled (all-zero) checkpoint columns from a partial run.
    keep = any(S.med ~= 0, 1);
    S.med = S.med(:, keep); w = w(keep);
    if S.hasBand, S.lo = S.lo(:, keep); S.hi = S.hi(:, keep); end

    assert(size(S.med,2) == numel(w), ...
        '%s: geometry has %d points but %s has %d values.', ...
        matfile, size(S.med,2), weight_var, numel(w));

    S.w = w;
    S.s = (w - min(w)) ./ (max(w) - min(w));         % normalized sweep position [0,1]
end

% ------------------------------------------------------------------------
function h = band(ax, x, ylo, yhi, c)
% Shaded percentile band.
    x = x(:)'; ylo = ylo(:)'; yhi = yhi(:)';
    h = fill(ax, [x fliplr(x)], [ylo fliplr(yhi)], c, ...
             'FaceAlpha', 0.18, 'EdgeColor', 'none', 'HandleVisibility','off');
end

% ------------------------------------------------------------------------
function [ref, deg] = ref_for(S, i, wsel)
% Value of parameter i at the selected weight (linear interp) = the reference
% "selected MAP" value. deg=true when that value is ~0, so a percent-of-selected
% normalization would be undefined/explode.
    v = S.med(i, :);
    if isscalar(S.w)
        ref = v(1);
    else
        ref = interp1(S.w, v, wsel, 'linear', 'extrap');
    end
    deg = abs(ref) < 1e-3 * max(max(abs(v)), eps);
end

% ------------------------------------------------------------------------
function hl = make_hl(w, wsel, frac)
% Map a selected weight and its +/-frac window to normalized sweep positions.
    wmin = min(w); wmax = max(w); rng = wmax - wmin;
    to_s = @(v) (v - wmin) ./ rng;
    clip = @(s) min(1, max(0, s));
    hl.s_lo  = clip(to_s(wsel*(1 - frac)));
    hl.s_hi  = clip(to_s(wsel*(1 + frac)));
    s_sel    = to_s(wsel);
    if s_sel < -0.02 || s_sel > 1.02        % selected weight outside swept range
        hl.s_sel = NaN;
    else
        hl.s_sel = clip(s_sel);
    end
end

% ------------------------------------------------------------------------
function draw_highlight(ax, hl, c)
% Shaded vertical band over the +/-frac weight window + dashed line at selected.
    if hl.s_hi > hl.s_lo
        xregion(ax, hl.s_lo, hl.s_hi, 'FaceColor', c, 'FaceAlpha', 0.12, ...
                'HandleVisibility', 'off');
    end
    if ~isnan(hl.s_sel)
        xline(ax, hl.s_sel, '--', 'Color', c, 'LineWidth', 1.1, ...
              'Alpha', 0.9, 'HandleVisibility', 'off');
    end
end
